#+TODO: FEATURE BUG DESIGN | DONE OBSOLETE

* Model
  I think I need to rethink the model. Isn't as easy as I would like
  for grouping, instancing, and draw order representation.

  A few things to consider:
  - *Multimethods* rather than increasingly complex ~condp~ statements.
  - Have a map of shapes. Do ordering, grouping, and intancing by
    reference. For example:
    #+begin_src clojure
      {;; A registry of shapes
       :shapes
       {:shape-id {:path [{:pos [1 1] :type :sharp}
                    {:pos [1 2] :type :smooth}]
             :material :mat-id}}

       ;; A registry of materials
       :materials
       {:mat-id {:fill "#FF00FF"
             :stroke-color "#FFFF00"
             :stroke-width "1px"}}

       ;; The explict draw order
       :layers [{:shape :shape-id
                 :tranform [[1 0 0]
                            [0 1 0]
                            [0 0 1]]}]}
    #+end_src
  - Maintaning matrix transformations would decouple us from the SVG's
    transformation representation. This frees us from the ~:offset-pos~
    style state that exist on the shapes currently.

* Features
** Math
*** FEATURE Matrix transformation library
    I need a basic library to handle translation, scale, and rotation
    of simple transformation matricies. Let's make one! This will
    enable us to work with raw points instead of awful CSS transforms.
** Navigation
*** Multitouch
**** BUG Need to scale with zoom level
** Tools
*** Grab
**** FEATURE Enable axis constrains with ~x~ and ~y~.
**** BUG Pressing invalid hotkey fails to cancel as expected.
*** Layer up/down
**** FEATURE Implement basic ability to modify draw order.
*** Duplicate
**** FEATURE Initial duplicate implemenation.
*** Path Tool
**** DESIGN Basic Design,
       - My hope is to add points at your current mouse position via
         the hotkeys ~s~ for sharp and ~r~ for round.
       - The round points will become quadratic SVG points.
       - I will need the ability to draw a tool overlay with the
         ability to click to select points.
